stages:
  split:
    cmd: python src/data/split_data.py
    deps:
    - data/raw_data/minerals_raw_data.csv
    - src/data/split_data.py
    outs:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
  normalize:
    cmd: python src/data/normalize.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - src/data/normalize.py
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
  gridsearch:
    cmd: python src/models/gridsearch.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - src/models/gridsearch.py
    outs:
    - models/best_params.pkl
  training:
    cmd: python src/models/training.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - models/best_params.pkl
    - src/models/training.py
    outs:
    - models/en_model.pkl
